/**
 * Source of `mcp-bridge.cjs`, which the plugin writes into its own folder when
 * Agent access is on.
 *
 * Claude Desktop only launches stdio servers. The bridge is that stdio server:
 * it reads newline-delimited JSON-RPC on stdin, POSTs each message to the
 * plugin's local HTTP endpoint, and writes the reply to stdout. It carries no
 * logic of its own and depends on nothing but node, so it never needs
 * updating separately from the plugin.
 */
export const BRIDGE_FILENAME = 'mcp-bridge.cjs';

export const BRIDGE_SOURCE = String.raw`#!/usr/bin/env node
// Simple Graph Builder: stdio <-> Obsidian MCP bridge. Generated by the plugin; edits are overwritten.
'use strict';
const http = require('http');

const url = new URL(process.env.SGB_MCP_URL || 'http://127.0.0.1:27180/mcp');
const token = process.env.SGB_MCP_TOKEN || '';
const META_VERSION = 'io.modelcontextprotocol/protocolVersion';

let buffer = '';
let pending = 0;
let ended = false;

process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
	buffer += chunk;
	let newline;
	while ((newline = buffer.indexOf('\n')) >= 0) {
		const line = buffer.slice(0, newline).trim();
		buffer = buffer.slice(newline + 1);
		if (line) forward(line);
	}
});
process.stdin.on('end', () => {
	ended = true;
	if (pending === 0) process.exit(0);
});

function write(message) {
	process.stdout.write(JSON.stringify(message) + '\n');
}

function headerValue(value) {
	return /^[\x20-\x7e]*$/.test(value) && !/^=\?base64\?.*\?=$/.test(value) && value.trim() === value
		? value
		: '=?base64?' + Buffer.from(value, 'utf8').toString('base64') + '?=';
}

function forward(line) {
	let message;
	try {
		message = JSON.parse(line);
	} catch (e) {
		write({ jsonrpc: '2.0', id: null, error: { code: -32700, message: 'Parse error' } });
		return;
	}
	const hasId = message && message.id !== undefined;
	const headers = {
		'content-type': 'application/json',
		accept: 'application/json, text/event-stream',
		authorization: 'Bearer ' + token,
	};
	const meta = message && message.params && message.params._meta;
	const version = meta && meta[META_VERSION];
	if (typeof version === 'string') {
		headers['mcp-protocol-version'] = version;
		headers['mcp-method'] = String(message.method);
		if (message.method === 'tools/call' && typeof message.params.name === 'string') {
			headers['mcp-name'] = headerValue(message.params.name);
		}
	}

	pending++;
	const done = () => {
		pending--;
		if (ended && pending === 0) process.exit(0);
	};
	const request = http.request(
		{ hostname: url.hostname, port: url.port, path: url.pathname, method: 'POST', headers },
		(response) => {
			let data = '';
			response.setEncoding('utf8');
			response.on('data', (d) => { data += d; });
			response.on('end', () => {
				if (hasId && data) {
					try {
						const reply = JSON.parse(data);
						// Transport errors (401, 403, ...) are sent without an id.
						if (reply && reply.id === undefined) reply.id = message.id;
						write(reply);
					} catch (e) {
						write({ jsonrpc: '2.0', id: message.id, error: { code: -32603, message: 'Bad reply from Obsidian (HTTP ' + response.statusCode + ')' } });
					}
				}
				done();
			});
		}
	);
	request.on('error', (err) => {
		if (hasId) {
			write({
				jsonrpc: '2.0',
				id: message.id,
				error: {
					code: -32603,
					message: 'Obsidian is not running, or Agent access is off in Simple Graph Builder settings (' + (err.code || err.message) + ').',
				},
			});
		}
		done();
	});
	request.end(JSON.stringify(message));
}
`;
