import { EffortLevel } from './extraction/providers/effort';

// ============================================
// Schema Version
// ============================================
export const GRAPH_SCHEMA_VERSION = 3;

// ============================================
// Legacy Types (v1) - kept for migration detection
// ============================================
export type LegacyNodeType = 'note' | 'entity' | 'keyword';
export type LegacyEdgeType = 'mentions' | 'matches_keyword' | 'relates_to' | 'links_to';

export interface LegacyGraphNode {
	id: string;
	type: LegacyNodeType;
	label: string;
	notePath?: string;
	createdAt?: number;
	updatedAt?: number;
}

export interface LegacyGraphEdge {
	id: string;
	source: string;
	target: string;
	type: LegacyEdgeType;
	createdAt?: number;
}

export interface LegacyGraphData {
	nodes: LegacyGraphNode[];
	edges: LegacyGraphEdge[];
	version: number;
}

// ============================================
// Ontology Model (v3)
// ============================================

/**
 * Entity types.
 *
 * The first 10 are the extraction vocabulary: the LLM must choose one of them
 * for each entity it returns. NOTE is different — it is generated by the plugin
 * for vault notes themselves and must never come back from a model, so it is
 * deliberately absent from EXTRACTION_ENTITY_TYPES below.
 */
export type EntityType =
	| 'PERSON'        // People, individuals, authors, researchers
	| 'ORGANIZATION'  // Companies, institutions, teams, communities
	| 'CONCEPT'       // Ideas, theories, principles, abstract notions
	| 'PROJECT'       // Projects, products, initiatives, goals
	| 'TOOL'          // Software, hardware, instruments, utilities
	| 'EVENT'         // Meetings, conferences, milestones, dates
	| 'PLACE'         // Locations, venues, geography
	| 'DOCUMENT'      // Papers, books, articles, notes, creative works
	| 'METHOD'        // Techniques, approaches, processes, workflows
	| 'TOPIC'         // Subjects, themes, fields, domains
	| 'NOTE';         // A vault note. Plugin-generated, never LLM-generated.

/**
 * The 10 types the LLM may return. Feeds the extraction JSON schema enum and
 * the prompt's type list — keep NOTE out of it, or models will start labelling
 * entities as notes.
 */
export const EXTRACTION_ENTITY_TYPES: readonly EntityType[] = [
	'PERSON',
	'ORGANIZATION',
	'CONCEPT',
	'PROJECT',
	'TOOL',
	'EVENT',
	'PLACE',
	'DOCUMENT',
	'METHOD',
	'TOPIC'
] as const;

/**
 * Every type a node may legitimately carry, including the plugin-generated NOTE.
 * Use this for validating nodes; use EXTRACTION_ENTITY_TYPES for anything that
 * describes what a model is allowed to produce.
 */
export const VALID_ENTITY_TYPES: readonly EntityType[] = [
	...EXTRACTION_ENTITY_TYPES,
	'NOTE',
] as const;

/**
 * Check if a string is a valid entity type
 */
export function isValidEntityType(type: string): type is EntityType {
	return VALID_ENTITY_TYPES.includes(type as EntityType);
}

// ============================================
// Entity Type Colors (shared across UI components)
// ============================================

/**
 * Color mapping for entity types.
 * Used in graph-view and neighborhood-view.
 */
export const ENTITY_TYPE_COLORS: Record<EntityType, string> = {
	PERSON: '#6366f1',       // indigo
	ORGANIZATION: '#8b5cf6', // violet
	CONCEPT: '#14b8a6',      // teal
	PROJECT: '#a855f7',      // purple
	TOOL: '#f59e0b',         // amber
	EVENT: '#ec4899',        // pink
	PLACE: '#22c55e',        // green
	DOCUMENT: '#3b82f6',     // blue
	METHOD: '#f97316',       // orange
	TOPIC: '#06b6d4',        // cyan
	NOTE: '#64748b',         // slate - vault notes, deliberately muted so the
	                         // entity layer stays the visual focus
};

/**
 * Get color for entity type with fallback for legacy labels.
 */
export function getEntityTypeColor(entityType: string | undefined): string {
	if (!entityType) {
		return '#94a3b8'; // default gray
	}

	const knownColor = ENTITY_TYPE_COLORS[entityType as EntityType];
	if (knownColor) {
		return knownColor;
	}

	// Fallback for legacy labels - use hash-based color
	let hash = 0;
	for (let i = 0; i < entityType.length; i++) {
		hash = entityType.charCodeAt(i) + ((hash << 5) - hash);
	}
	const hue = Math.abs(hash) % 360;
	return `hsl(${hue}, 70%, 60%)`;
}

/**
 * Get entity type from a node with consistent fallback logic.
 * Handles both new (entityType) and legacy (label) fields.
 */
export function getNodeEntityType(node: { entityType?: EntityType; label?: string }): EntityType {
	if (node.entityType && isValidEntityType(node.entityType)) {
		return node.entityType;
	}
	if (node.label) {
		return labelToEntityType(node.label);
	}
	return 'CONCEPT';
}

/**
 * Get relationship verb from an edge with consistent fallback logic.
 * Handles both new (relationship) and legacy (type) fields.
 */
export function getEdgeRelationship(edge: { relationship?: string; type?: string }): string {
	if (edge.relationship) {
		return edge.relationship;
	}
	if (edge.type) {
		// Try to convert legacy type to verb
		const legacyTypeMap: Record<string, string> = {
			'HAS_PART': 'contains',
			'LEADS_TO': 'leads to',
			'ACTED_ON': 'acts on',
			'CITES': 'cites',
			'RELATED_TO': 'relates to',
		};
		return legacyTypeMap[edge.type.toUpperCase()] || edge.type;
	}
	return 'relates to';
}

/**
 * Ontology node with fixed entity types.
 */
export interface OntologyNode {
	id: string;
	entityType: EntityType;  // MUST be one of the 10 types
	label?: string;          // Legacy: kept for backwards compatibility
	properties: {
		name: string;          // display name (required)
		aliases?: string[];    // alternative names for this entity (for resolution)
		description?: string;  // brief description from LLM
		[key: string]: unknown;  // additional properties
	};
	sourceNotes: string[];   // note paths that reference this node
	createdAt?: number;
	updatedAt?: number;
}

/**
 * Ontology edge with free-form relationship verbs.
 */
export interface OntologyEdge {
	id: string;
	source: string;          // source node ID
	target: string;          // target node ID
	relationship: string;    // free-form verb (e.g., "develops", "uses", "causes")
	type?: string; // Legacy: kept for backwards compatibility
	properties: {
		detail?: string;       // optional: additional context
		[key: string]: unknown;  // additional properties
	};
	sourceNote?: string;     // note path that created this relationship
	createdAt?: number;
}

/**
 * Graph data structure (v2 schema)
 */
// ============================================
// Text normalization
// ============================================

/**
 * Canonical Unicode form for any text the plugin stores or displays.
 *
 * Korean is the reason this exists. Hangul has two equivalent encodings:
 * composed syllables (NFC, "머신러닝" = 4 code points) and conjoining jamo
 * (NFD, the same 4 glyphs as 10 code points). They render identically and
 * compare unequal, and `toLowerCase()` does nothing to reconcile them. macOS
 * filenames are NFD, so a name pasted from a file path and the same name typed
 * into a note produce two different strings.
 */
export function normalizeUnicode(text: string): string {
	return text.normalize('NFC');
}

/**
 * Canonical key for matching a name, alias, or path.
 *
 * NFC first, then case-folded, then whitespace runs collapsed. Without the NFC
 * step the two Hangul encodings above yield different node IDs (duplicate
 * entities for one concept) and a bigram Jaccard score of exactly 0 between a
 * word and itself, which silently defeated the Korean search support.
 *
 * Deliberately does NOT strip spaces entirely: "머신 러닝" and "머신러닝" stay
 * distinct here, because the same rule would fuse unrelated Latin names. Search
 * handles that looser matching via bigrams; entity resolution handles it via
 * the LLM and embeddings.
 */
export function normalizeKey(text: string): string {
	return normalizeUnicode(text).toLowerCase().replace(/\s+/g, ' ').trim();
}

/**
 * True for an edge produced by the old entity-level wikilink pass.
 *
 * That pass connected every entity in a note to every entity in each linked
 * note — O(L*k^2) edges where one per note pair was intended. On a real 141-note
 * vault it produced 188,097 of 191,436 edges (98.3%) and a 115 MB data.json.
 * The note layer replaces it; this predicate identifies the leftovers so they
 * can be pruned on load.
 *
 * Lives here rather than in graph/merge.ts to keep it importable from
 * graph/cache.ts without creating a cache -> merge -> resolver -> cache cycle.
 */
export function isLegacyWikilinkEdge(edge: OntologyEdge): boolean {
	return edge.relationship === 'links to' && edge.properties?.detail === 'wikilink';
}

/**
 * Prefix for the id of a NOTE node. Every note-layer edge starts at one, which
 * is what makes the layer identifiable without consulting the node table.
 */
export const NOTE_ID_PREFIX = 'note:';

/** True for a node the plugin generated to represent a vault note. */
export function isNoteNode(node: OntologyNode): boolean {
	return node.entityType === 'NOTE';
}

/** The only two verbs the note layer ever produces. */
const NOTE_LAYER_VERBS = new Set(['mentions', 'links to']);

/**
 * True for an edge of the note layer: `mentions` (note -> entity) and
 * `links to` (note -> note).
 *
 * The whole layer is derived data. `mentions` restates `node.sourceNotes`, and
 * `links to` restates Obsidian's own `metadataCache.resolvedLinks`, so
 * rebuildNoteLayer can reproduce all of it on load from information that is
 * already there. Since mentions are one edge per (note, entity) pair they are
 * also the largest population in the graph -- persisting them cost about 40% of
 * data.json for nothing.
 *
 * The verb has to be checked, not just the id prefix. v2 built node ids from
 * the LLM's free-form label, and models do label things "Note" -- see `'note'`
 * in labelToEntityType's DOCUMENT list. A legacy paper called
 * `note:attention is all you need` therefore has a `note:` id while being an
 * ordinary entity, and matching on the prefix alone would delete every real
 * relationship it has. Callers with the node table at hand should prefer
 * `noteNodeIds`, which decides by entity type instead of by string.
 */
export function isNoteLayerEdge(edge: OntologyEdge, noteIds?: Set<string>): boolean {
	if (noteIds?.has(edge.source)) return true;
	return edge.source.startsWith(NOTE_ID_PREFIX) && NOTE_LAYER_VERBS.has(edge.relationship);
}

/** Ids of every NOTE node in a collection, for the check above. */
export function noteNodeIds(nodes: OntologyNode[]): Set<string> {
	const ids = new Set<string>();
	for (const node of nodes) if (isNoteNode(node)) ids.add(node.id);
	return ids;
}

export interface GraphData {
	nodes: OntologyNode[];
	edges: OntologyEdge[];
	version: number;        // schema version (should be 2)
}

// ============================================
// LLM Extraction Types
// ============================================

/**
 * Raw node from LLM extraction (before ID normalization)
 */
export interface RawExtractionNode {
	id: string;              // temporary ID used within extraction
	entityType: EntityType;  // MUST be one of the 10 types
	label?: string;          // Legacy: kept for backwards compatibility
	properties: {
		name: string;
		description?: string;
		[key: string]: unknown;
	};
}

/**
 * Raw relationship from LLM extraction (before ID normalization)
 */
export interface RawExtractionRelationship {
	source: string;          // temporary ID from extraction
	target: string;          // temporary ID from extraction
	relationship: string;    // free-form verb (e.g., "develops", "uses")
	type?: string; // Legacy: kept for backwards compatibility
	properties: {
		detail?: string;       // optional description
		[key: string]: unknown;
	};
}

/**
 * LLM extraction result
 */
export interface OntologyExtractionResult {
	nodes: RawExtractionNode[];
	relationships: RawExtractionRelationship[];
}

// ============================================
// Graph Search Types (for smart search tools)
// ============================================

export interface SearchNodeResult {
	name: string;
	entityType: EntityType;
	label?: string;          // Legacy: for backwards compatibility
	score: number;
}

export interface RelationshipResult {
	from: string;
	to: string;
	relationship: string;    // free-form verb
	type?: string; // Legacy: for backwards compatibility
	detail?: string;
}

export interface ConnectedNodeResult {
	name: string;
	entityType: EntityType;
	label?: string;          // Legacy: for backwards compatibility
	path: string[];
}

export interface PathStep {
	node: string;
	via?: string;            // free-form relationship verb
	detail?: string;
}

export interface PathResult {
	found: boolean;
	path: PathStep[];
}

export interface SourceNoteResult {
	path: string;
	title: string;
}

// ============================================
// API & Settings
// ============================================

export type ApiProvider = 'claude' | 'openai' | 'gemini' | 'ollama';

/**
 * Embedding provider options.
 * Note: Claude doesn't have an embeddings API, so it's not included here.
 */
export type EmbeddingProvider = 'openai' | 'gemini' | 'ollama';

/**
 * Extraction mode controls how thorough the entity extraction is.
 * - standard: Max 15 entities per chunk (fast, low cost)
 * - thorough: No limits on entities per chunk (comprehensive)
 */
export type ExtractionMode = 'standard' | 'thorough';

/**
 * Which API a local LLM server speaks.
 * - ollama: Ollama's native /api/chat
 * - openai: the OpenAI Chat Completions API, as served by llama.cpp's
 *   llama-server, LM Studio, vLLM, LiteLLM and similar
 */
export type LocalApiStyle = 'ollama' | 'openai';

export interface Settings {
	apiProvider: ApiProvider;
	/**
	 * Legacy single shared key, superseded by `apiKeys` but still honoured as a
	 * fallback so installs that predate per-provider keys keep working.
	 */
	apiKey: string;
	/** Per-provider API keys, so a cross-provider Smart Search sends the right one. */
	apiKeys: Partial<Record<ApiProvider, string>>;
	// Model selection per provider (for KG building / extraction)
	claudeModel: string;
	openaiModel: string;
	geminiModel: string;
	ollamaModel: string;
	ollamaHost: string;     // Local server URL (default: http://localhost:11434)
	localApiStyle: LocalApiStyle;  // default: 'ollama'
	// Extraction settings
	extractionMode: ExtractionMode;  // Controls extraction thoroughness
	extractionEffort: EffortLevel;   // default: 'minimal' - reasoning depth for extraction
	// Auto-analysis
	autoAnalyzeOnSave: boolean;  // Analyze notes automatically when saved
	// Smart Search model settings (separate from extraction)
	useSeparateSmartSearchModel: boolean;  // default: false - use same model as extraction
	smartSearchProvider: ApiProvider;      // default: same as apiProvider
	smartSearchClaudeModel: string;
	smartSearchOpenaiModel: string;
	smartSearchGeminiModel: string;
	smartSearchOllamaModel: string;
	smartSearchEffort: EffortLevel;        // default: 'minimal'
	// View settings
	openGraphInMain: boolean;    // Open graph view in main window instead of sidebar
	graphMinDegree: number;      // Minimum connections to show node in graph (default: 0)
	graphShowNotes: boolean;     // Show NOTE nodes and their edges in the graph (default: true)
	// Embedding-based entity resolution (opt-in)
	enableEmbeddings: boolean;            // default: false - embeddings are opt-in to avoid API costs
	embeddingProvider: EmbeddingProvider; // default: 'openai'
	embeddingApiKey: string;              // separate key for embeddings (can differ from main provider)
	embeddingModel: string;               // default: 'text-embedding-3-small'
	embeddingHost: string;                // local embedding server; blank = reuse the chat server's host
	embeddingLocalApiStyle: LocalApiStyle; // API the local embedding server speaks; independent of the chat provider
	resolutionThresholdHigh: number;      // default: 0.90 - auto-merge above this
	resolutionThresholdLow: number;       // default: 0.80 - LLM verification between low and high
	enableLLMVerification: boolean;       // default: true - use LLM for ambiguous matches
	// Vault write-back (opt-in). Turns the extracted graph into real Obsidian
	// links so it also appears in the native graph view, backlinks and
	// properties. Everything here is off by default: it writes to user notes.
	enableEntityNotes: boolean;      // master toggle - create one note per entity
	entityFolder: string;            // default: 'Entities'
	writeRelationshipsSection: boolean; // list relationships as links in entity notes
	enableRelatedWriteback: boolean; // add a `related:` property to analyzed notes
	relatedPropertyName: string;     // default: 'related'
	// Migration bookkeeping. Bump when a migration step is added; see
	// src/settings-migration.ts.
	settingsVersion: number;
}

// Legacy type for compatibility with GraphNode references
export interface GraphNode {
	id: string;
	type: 'note' | 'entity' | 'keyword';
	label: string;
	notePath?: string;
}

// ============================================
// Content Hash Tracking
// ============================================

export interface NoteHash {
	path: string;
	hash: string;
	analyzedAt: number;     // timestamp of last analysis
}

export interface HashData {
	hashes: NoteHash[];
}

// ============================================
// Plugin Data Structure
// ============================================

// ============================================
// Entity Resolution Types
// ============================================

/**
 * Index metadata for binary embedding storage.
 * The actual embeddings are stored in a separate binary file.
 */
export interface EmbeddingIndex {
	nodeIds: string[];       // Ordered list of node IDs (index i corresponds to embedding i in binary file)
	model: string;           // e.g., "text-embedding-3-small"
	dimensions: number;      // 1536 for OpenAI, 768 for Gemini
	updatedAt: number;       // timestamp of last update
}

/**
 * Persistent resolution cache: maps raw tokens to canonical node IDs.
 * Used to remember previous resolution decisions across sessions.
 */
export interface ResolutionCache {
	[rawToken: string]: string;  // raw token (lowercase) → canonical node ID
}

/**
 * Result of entity resolution attempt.
 */
export interface ResolutionResult {
	nodeId: string;          // The resolved or newly created node ID
	matchType: 'cached' | 'session' | 'exact' | 'alias' | 'embedding_high' | 'embedding_verified' | 'new';
	confidence: number;      // 0.0 to 1.0
	mergedInto?: string;     // If merged, the name of the target node
}

/**
 * Stats from resolution during merge operation.
 */
export interface ResolutionStats {
	cached: number;          // resolved via persistent cache
	session: number;         // resolved via session cache
	exact: number;           // resolved via exact name match
	alias: number;           // resolved via alias match
	embeddingHigh: number;   // resolved via high-confidence embedding (auto-merge)
	embeddingVerified: number; // resolved via LLM-verified embedding match
	new: number;             // created as new entity
}

/**
 * Plugin data structure (stored via loadData/saveData)
 */
export interface PluginData {
	settings: Settings;
	graph: GraphData;
	hashes: HashData;
	resolutionCache?: ResolutionCache;   // Persistent token → node ID mappings
	embeddingIndex?: EmbeddingIndex;     // Metadata for embeddings.bin
}

/**
 * Map legacy label to EntityType for migration.
 */
export function labelToEntityType(label: string): EntityType {
	const labelLower = label.toLowerCase();

	// Person-related
	if (['person', 'author', 'researcher', 'individual'].includes(labelLower)) return 'PERSON';
	if (['team', 'group'].includes(labelLower)) return 'ORGANIZATION';

	// Organization-related
	if (['organization', 'company', 'institution', 'community'].includes(labelLower)) return 'ORGANIZATION';

	// Concept-related
	if (['concept', 'theory', 'principle', 'idea'].includes(labelLower)) return 'CONCEPT';

	// Project-related
	if (['project', 'product', 'system', 'initiative', 'application'].includes(labelLower)) return 'PROJECT';

	// Tool-related
	if (['tool', 'library', 'framework', 'software', 'hardware', 'instrument'].includes(labelLower)) return 'TOOL';

	// Event-related
	if (['event', 'meeting', 'conference', 'milestone'].includes(labelLower)) return 'EVENT';

	// Place-related
	if (['place', 'location', 'venue', 'geography'].includes(labelLower)) return 'PLACE';

	// Document-related
	if (['document', 'paper', 'book', 'article', 'note'].includes(labelLower)) return 'DOCUMENT';

	// Method-related
	if (['method', 'technique', 'approach', 'process', 'workflow'].includes(labelLower)) return 'METHOD';

	// Topic-related
	if (['topic', 'subject', 'theme', 'field', 'domain'].includes(labelLower)) return 'TOPIC';

	// Default to CONCEPT for unknown labels
	return 'CONCEPT';
}

/**
 * Check if graph data is v1 (legacy) format
 */
export function isLegacyGraphData(data: unknown): boolean {
	if (!data || typeof data !== 'object') return false;
	const graphData = data as { nodes?: unknown[]; version?: number };
	if (!graphData.nodes || !Array.isArray(graphData.nodes)) return false;
	if (graphData.nodes.length === 0) return false;

	// Check if first node has 'type' property (v1) instead of 'label' with 'properties' (v2)
	const firstNode = graphData.nodes[0] as Record<string, unknown>;
	return 'type' in firstNode && !('properties' in firstNode);
}
